version: latest
services:
  api:
    build:
      context: ./
    ports:
      - 5000:5000
    depends_on:
      - minio
    networks:
      - lab-antifraude

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=guestguest
    volumes:
      - ~/.minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - lab-antifraude

networks:
  lab-antifraude: