version: latest
services:
  app:
    build: .
    ports:
      - 5000:5000
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 1
      start_period: 10s
      start_interval: 3s
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data
volumes:
  redis:
