apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-relatorios
spec:
  selector:
    matchLabels:
      app: api-relatorios
  template:
    metadata:
      labels:
        app: api-relatorios
    spec:
      containers:
      - name: api-relatorios
        image: cesarpiau/lab-api-relatorios:latest
        env:
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: config-ferramentas
              key: MINIO_ENDPOINT
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: config-ferramentas
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-ferramentas
              key: MINIO_ROOT_PASSWORD
        resources:
          limits:
            memory: "256Mi"
            cpu: "300m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-relatorios
spec:
  selector:
    app: api-relatorios
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30004
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ingress-api
spec:
  rules:
    - host: adalab.eastus.cloudapp.azure.com
      http:
        paths:
          - path: /api(/|$)(.*)
            backend:
              service:
                name: api-relatorios
                port:
                  number: 5000
            pathType: Prefix
  ingressClassName: nginx