apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        - containerPort: 9001
        readinessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 5
        env:
          - name:  MINIO_ROOT_USER
            valueFrom:
              configMapKeyRef:
                name: config-ferramentas
                key: MINIO_ROOT_USER
          - name:  MINIO_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-ferramentas
                key: MINIO_ROOT_PASSWORD
        args:
        - server
        - /data
        - --console-address
        - ":9001"
        volumeMounts:
          - name:  minio-data
            mountPath: /data
      volumes:
      - name: minio-data
        persistentVolumeClaim:
          claimName: minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - name: api
    port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-console
spec:
  selector:
    app: minio
  ports:
  - name: console
    port: 9001
    targetPort: 9001
    nodePort: 30003
  type: NodePort