version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 1s
      retries: 3
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - lab-antifraude
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - lab-antifraude

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=guestguest
    volumes:
      - ~/.minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - lab-antifraude

  producer:
    build:
      context: /producer
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    networks:
      - lab-antifraude

  consumer:
    build:
      context: /consumer
    depends_on:
      - producer
    networks:
      - lab-antifraude

networks:
  lab-antifraude: