version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - lab-antifraude
  
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - lab-antifraude

  minio:
    image: quay.io/minio/minio
    healthcheck:
      test: curl http://minio:9000/minio/health/live
      interval: 5s
      timeout: 1s
      retries: 3
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=guestguest
    volumes:
      - ~/.minio/data:/data
    command: server /data --console-address ":9001"
    networks:
      - lab-antifraude

  reverse-proxy:
    image: traefik:v2.11
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - lab-antifraude

  producer:
    build:
      context: /producer
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=guestguest
      - MINIO_ENDPOINT=minio:9000
      - RABBITMQ_HOST=rabbitmq
    networks:
      - lab-antifraude

  consumer:
    build:
      context: /consumer
    depends_on:
      - producer
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=guestguest
      - MINIO_ENDPOINT=minio:9000
      - RABBITMQ_HOST=rabbitmq
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - lab-antifraude

  api:
    build:
      context: /api
    ports:
      - 5000:5000
    environment:
      - MINIO_ROOT_USER=guest
      - MINIO_ROOT_PASSWORD=guestguest
      - MINIO_ENDPOINT=minio:9000
    depends_on:
      minio:
        condition: service_healthy
        restart: true
    networks:
      - lab-antifraude

networks:
  lab-antifraude: